import Head from "next/head";

import { getAllPosts } from "./api/posts";

import styles from "../styles/Home.module.css";

import SideNav from "../components/nav";
import Post from "../components/post";
import thumbnail from "./api/thumbnail";

interface HomeProps {
  posts: Array<{
    slug: string;
    title: string;
    description: string;
    thumbnailUrl: string;
  }>;
}

export default function Home(props: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <SideNav />
      </header>
      <main className={styles.main}>
        {props.posts.map((post, idx) => (
          <Post
            key={idx}
            postLink={post.slug}
            title={post.title}
            description={post.description}
            thumbnailUrl={post.thumbnailUrl}
          />
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const allPosts = await getAllPosts();

  return {
    props: {
      posts: allPosts,
    },
  };
}
