import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import SideNav from "../components/sidenav";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <SideNav />
      </header>
      <main className={styles.main}></main>
    </div>
  );
}
